"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Table, TableBody, TableRow, TableCell, TableHead, TableHeader } from "@/components/ui/table";
import { Employee, Finance, Snapshot, addWorkDays, blankEmployee, employeeFields, employeeMatchesSearch, validateEmployee, readableError, statuses, today, kwd, remaining, balance, number } from "@/lib/hr";
import { Avatar, Choice, Field, SaveButton } from "./ui-parts";
import { toast } from "sonner";
import { Check, ImagePlus, Search, Trash2 } from "lucide-react";

export type Commit=(body:Record<string,unknown>)=>Promise<boolean>;
export type ModalState={type:"employee";employee?:Employee}|{type:"bulk";ids:string[]}|{type:"finance";kind:"loan"|"obligation";employeeId?:string}|{type:"payment";finance:Finance}|{type:"leave";ids:string[];kind?:"annual"|"holiday"}|null;
export default function Forms({modal,close,s,busy,commit}:{modal:ModalState;close:()=>void;s:Snapshot;busy:boolean;commit:Commit}){
  if(!modal)return null;
  const titles={employee:modal.type==="employee"&&modal.employee?"تعديل بيانات الموظف":"إضافة موظف جديد",bulk:"تحديث جماعي",finance:modal.type==="finance"&&modal.kind==="loan"?"إضافة قرض موظف":"إضافة خصم",payment:"تسجيل دفعة",leave:"حركة رصيد إجازة"};
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)close();}}><DialogContent className={"app-dialog "+(["employee","bulk"].includes(modal.type)?"large-dialog":"")} dir="rtl"><DialogHeader><DialogTitle>{titles[modal.type]}</DialogTitle><DialogDescription>{modal.type==="bulk"?"راجع القيم الحالية والجديدة قبل تطبيق التغيير.":modal.type==="employee"?"الاسم والرقم الوظيفي مطلوبان. يمكنك استكمال بقية البيانات لاحقاً.":"تُحفظ الحركة في سجل العمليات بعد التأكيد."}</DialogDescription></DialogHeader>{modal.type==="employee"?<EmployeeForm initial={modal.employee} s={s} busy={busy} commit={commit}/>:modal.type==="bulk"?<BulkForm ids={modal.ids} s={s} busy={busy} commit={commit}/>:modal.type==="finance"?<FinanceForm kind={modal.kind} employeeId={modal.employeeId} s={s} busy={busy} commit={commit}/>:modal.type==="payment"?<PaymentForm finance={modal.finance} s={s} busy={busy} commit={commit}/>:<LeaveForm ids={modal.ids} kind={modal.kind||"annual"} s={s} busy={busy} commit={commit}/>}</DialogContent></Dialog>;
}
function EmployeeForm({initial,s,busy,commit}:{initial?:Employee;s:Snapshot;busy:boolean;commit:Commit}){
  const [e,setE]=useState<Employee>(()=>initial?{...blankEmployee(),...initial}:blankEmployee());const [error,setError]=useState("");
  async function changePhoto(file?:File|null){
    if(!file)return;
    setError("");
    try{const photoDataUrl=await compressEmployeePhoto(file);setE(prev=>({...prev,photoDataUrl}));}
    catch(err){setError(readableError(err));}
  }
  return <form onSubmit={async ev=>{ev.preventDefault();setError("");try{const employee=validateEmployee(e,s.employees,s.leaves);await commit({action:"employee.save",employee});}catch(err){setError(readableError(err));}}}>
    <div className="photo-field"><Avatar name={e.name} src={e.photoDataUrl}/><div><strong>صورة الموظف</strong><p>ارفع صورة شخصية واضحة. سيتم ضغطها تلقائياً قبل الحفظ.</p><label className="photo-upload"><ImagePlus size={17}/>اختيار صورة<input type="file" accept="image/png,image/jpeg,image/webp" onChange={ev=>void changePhoto(ev.target.files?.[0])}/></label>{e.photoDataUrl&&<button type="button" className="photo-remove" onClick={()=>setE({...e,photoDataUrl:""})}><Trash2 size={15}/>حذف الصورة</button>}</div></div>
    <div className="form-grid">{employeeFields.map(f=><Field key={f.key} label={f.label+(["name","code"].includes(f.key)?" *":"")} wide={f.key==="notes"} hint={f.key==="probationEnd"?"يُحسب تلقائياً بعد 100 يوم عمل من تاريخ التعيين مع استبعاد الجمعة والسبت.":f.key==="annualOpening"||f.key==="holidayOpening"?"رصيد افتتاحي؛ حركات الإضافة والخصم تُضاف إليه بشكل مستقل.":undefined}>{f.key==="status"?<Choice label={f.label} value={e.status} options={[...statuses]} onChange={v=>setE({...e,status:v as Employee["status"]})}/>:f.key==="allowanceType"?<Choice label={f.label} value={e.allowanceType} options={[{value:"",label:"بدون بدل"},...(s.settings.allowanceTypes||[]).map(x=>({value:x,label:x}))]} onChange={v=>setE({...e,allowanceType:v})}/>:f.key==="notes"?<textarea aria-label={f.label} value={e.notes} maxLength={2000} onChange={ev=>setE({...e,notes:ev.target.value})}/>:<input aria-label={f.label} type={f.type==="money"||f.type==="days"?"number":f.type||"text"} readOnly={f.key==="probationEnd"} required={["name","code"].includes(f.key)} min={f.type==="money"||f.type==="days"?0:undefined} max={f.type==="days"?9999:undefined} step={f.type==="money"?"0.001":f.type==="days"?"0.5":undefined} maxLength={f.key==="civilId"?12:160} dir={f.type==="date"||f.type==="money"||["civilId","phone","email","code"].includes(f.key)?"ltr":undefined} value={f.type==="money"?Number(e[f.key])/1000:String(e[f.key])} onChange={ev=>{const value=f.type==="money"?Math.round(Number(ev.target.value)*1000):f.type==="days"?Number(ev.target.value):ev.target.value;setE({...e,[f.key]:value,...(f.key==="startDate"?{probationEnd:addWorkDays(String(value),100)}:{})});}}/>}</Field>)}</div>
    {error&&<p role="alert" className="error-box">{error}</p>}<div className="form-footer"><SaveButton busy={busy}/></div>
  </form>;
}
async function compressEmployeePhoto(file:File):Promise<string>{
  if(!/^image\/(png|jpeg|webp)$/i.test(file.type))throw Error("استخدم صورة PNG أو JPG أو WEBP فقط.");
  if(file.size>5*1024*1024)throw Error("حجم الصورة أكبر من 5 ميجابايت.");
  const bitmap=await createImageBitmap(file);const max=512,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext("2d");if(!ctx)throw Error("تعذر تجهيز الصورة.");ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const data=canvas.toDataURL("image/jpeg",0.78);bitmap.close();if(data.length>650000)throw Error("الصورة ما زالت كبيرة بعد الضغط. اختر صورة أصغر.");return data;
}
function BulkForm({ids,s,busy,commit}:{ids:string[];s:Snapshot;busy:boolean;commit:Commit}){
  const [key,setKey]=useState("department"),[value,setValue]=useState(""),[preview,setPreview]=useState(false),[confirmed,setConfirmed]=useState(false),[error,setError]=useState("");
  const money=["salaryFils","allowancesFils"].includes(key),numeric=money||["annualOpening","holidayOpening"].includes(key);const fields=employeeFields.filter(f=>["department","branch","status","salaryFils","allowanceType","allowancesFils","annualOpening","holidayOpening"].includes(f.key));
  const next=money?Math.round(Number(value)*1000):numeric?Number(value):value;
  const patch={[key]:next};const chosen=s.employees.filter(e=>ids.includes(e.id));
  return <form onSubmit={async ev=>{ev.preventDefault();setError("");try{if(!value.trim())throw Error("أدخل القيمة الجديدة");chosen.forEach(e=>validateEmployee({...e,...patch},s.employees,s.leaves));if(!preview){setPreview(true);return;}if(!confirmed)throw Error("أكّد مراجعة التغييرات");await commit({action:"employees.bulk",ids,patch});}catch(e){setError(readableError(e));}}}>
    <div className="notice">سيتم استبدال الحقل المحدد لدى <strong>{ids.length} موظف</strong>. لتزويد رصيد قائم بأيام إضافية استخدم «حركة رصيد» في قسم الإجازات.</div>
    <div className="form-grid"><Field label="الحقل المطلوب تحديثه"><Choice label="حقل التحديث" value={key} onChange={v=>{setKey(v);setValue(v==="status"?statuses[0]:"");setPreview(false);setConfirmed(false);}} options={fields.map(f=>({value:f.key,label:f.label}))}/></Field><Field label="القيمة الجديدة">{key==="status"?<Choice label="الحالة الجديدة" value={value} options={[...statuses]} onChange={v=>{setValue(v);setPreview(false);setConfirmed(false);}}/>:key==="allowanceType"?<Choice label="نوع البدل" value={value} options={[{value:"",label:"بدون بدل"},...(s.settings.allowanceTypes||[]).map(x=>({value:x,label:x}))]} onChange={v=>{setValue(v);setPreview(false);setConfirmed(false);}}/>:<input aria-label="القيمة الجديدة" required type={numeric?"number":"text"} step={money?"0.001":numeric?"0.5":undefined} min={numeric?0:undefined} value={value} onChange={ev=>{setValue(ev.target.value);setPreview(false);setConfirmed(false);}}/>}</Field></div>
    {preview&&<><div className="preview-table"><Table><TableHeader><TableRow><TableHead>الموظف</TableHead><TableHead>القيمة الحالية</TableHead><TableHead>القيمة الجديدة</TableHead></TableRow></TableHeader><TableBody>{chosen.map(e=><TableRow key={e.id}><TableCell>{e.name}</TableCell><TableCell>{money?kwd(Number(e[key as keyof Employee])):String(e[key as keyof Employee])||"—"}</TableCell><TableCell className="purple-text">{value}</TableCell></TableRow>)}</TableBody></Table></div><label className="check-line"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/>راجعت التغييرات وأوافق على تطبيقها على المحددين.</label></>}
    {error&&<p className="error-box" role="alert">{error}</p>}<div className="form-footer"><SaveButton busy={busy}>{preview?"تطبيق التحديث الجماعي":"معاينة التغييرات"}</SaveButton></div>
  </form>;
}
function FinanceForm({kind,employeeId,s,busy,commit}:{kind:"loan"|"obligation";employeeId?:string;s:Snapshot;busy:boolean;commit:Commit}){
  const [f,setF]=useState({employeeId:employeeId||"",employeeIds:employeeId?[employeeId]:[] as string[],kind,title:"",amountFils:0,installmentFils:0,startDate:today(),dueDate:"",notes:"",loanType:(s.settings.inputTypes||[])[0]||"التزام",installmentsCount:0,firstInstallmentDate:today(),lender:"",deductionMode:"fixed" as "fixed"|"percent"|"cash",deductionPercent:0,priority:10,paused:false});const [employeeQuery,setEmployeeQuery]=useState("");const matchingEmployees=s.employees.filter(e=>e.status!=="انتهت خدمته"&&employeeMatchesSearch(e,employeeQuery));
  const installments=f.amountFils&&f.installmentFils?Math.ceil(f.amountFils/f.installmentFils):0;
  const employeePicker=<Field label={kind==="loan"?"الموظفون *":"الموظفون *"} wide hint="ابحث بأي جزء من الاسم أو الرقم الوظيفي أو الهوية أو الهاتف أو الإدارة أو الوظيفة، ثم اختر موظفاً أو أكثر."><div className="search-control finance-employee-search"><Search size={17}/><input placeholder="البحث في جميع بيانات الموظف…" value={employeeQuery} onChange={e=>setEmployeeQuery(e.target.value)}/></div><div className="employee-multi-list">{matchingEmployees.map(e=><label key={e.id}><Checkbox checked={f.employeeIds.includes(e.id)} onCheckedChange={v=>setF({...f,employeeId:v===true?e.id:f.employeeId,employeeIds:v===true?[...new Set([...f.employeeIds,e.id])]:f.employeeIds.filter(id=>id!==e.id)})}/><span>{e.name}<small>{e.code} · {e.civilId||e.phone||e.department||"—"}</small></span></label>)}</div></Field>;
  return <form onSubmit={async e=>{e.preventDefault();const ids=f.employeeIds;if(!ids.length){toast.error("اختر موظفاً واحداً على الأقل");return;}const amount=kind==="obligation"?f.amountFils:f.amountFils,installment=kind==="obligation"?f.amountFils:f.installmentFils;await commit({action:"finance.add",finance:{...f,employeeId:ids[0],employeeIds:ids,title:f.title,amountFils:amount,installmentFils:installment,installmentsCount:kind==="loan"?installments:0,dueDate:"",lender:"",priority:0,loanType:kind==="loan"?"":f.title,deductionMode:undefined,deductionPercent:0,paused:false}});}}><div className="form-grid">{employeePicker}{kind==="loan"?<><Field label="اسم القرض / السبب *" wide><input required minLength={2} maxLength={160} value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></Field><Field label="أصل المبلغ (د.ك) *"><input required type="number" min="0.001" step="0.001" value={f.amountFils/1000||""} onChange={e=>setF({...f,amountFils:Math.round(Number(e.target.value)*1000)})}/></Field><Field label="القسط الشهري (د.ك) *"><input type="number" required min="0.001" step="0.001" value={f.installmentFils/1000||""} onChange={e=>setF({...f,installmentFils:Math.round(Number(e.target.value)*1000)})}/></Field><Field label="عدد الأقساط"><input readOnly value={installments||""} aria-label="عدد الأقساط المحسوب"/></Field><Field label="تاريخ أول قسط"><input type="date" value={f.firstInstallmentDate} onChange={e=>setF({...f,firstInstallmentDate:e.target.value})}/></Field></>:<><Field label="نوع الخصم *" wide hint="اكتب نوع الخصم يدويًا أو اختر من القائمة الجاهزة."><input required minLength={2} maxLength={160} list="deduction-types" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><datalist id="deduction-types">{(s.settings.inputTypes||[]).map(x=><option key={x} value={x}/>)}</datalist></Field><Field label="قيمة الخصم (د.ك) *"><input required type="number" min="0.001" step="0.001" value={f.amountFils/1000||""} onChange={e=>setF({...f,amountFils:Math.round(Number(e.target.value)*1000)})}/></Field></>}<Field label="تاريخ البداية *"><input required type="date" value={f.startDate} onChange={e=>setF({...f,startDate:e.target.value})}/></Field><Field label="ملاحظات" wide><textarea value={f.notes} maxLength={2000} onChange={e=>setF({...f,notes:e.target.value})}/></Field></div><p className="form-hint">{kind==="loan"?"عدد الأقساط يُحسب تلقائيًا من أصل المبلغ وقيمة القسط.":"يمكن تسجيل الخصم لموظف واحد أو مجموعة موظفين، أو رفع الخصومات من Excel من صفحة الاستيراد."}</p><div className="form-footer"><SaveButton busy={busy}/></div></form>;
}
function PaymentForm({finance:f,s,busy,commit}:{finance:Finance;s:Snapshot;busy:boolean;commit:Commit}){
  const left=remaining(f,s.payments);const [full,setFull]=useState(false);const [p,setP]=useState({financeId:f.id,amountFils:Math.min(f.installmentFils||left,left),date:today(),notes:""});
  return <form onSubmit={async e=>{e.preventDefault();await commit({action:"payment.add",payment:{...p,amountFils:full?left:p.amountFils}});}}><div className="amount-banner"><span>{f.title} · المبلغ المتبقي</span><strong dir="ltr">{kwd(left)} <small>د.ك</small></strong></div><div className="form-grid"><Field label="قيمة الدفعة (د.ك)"><input aria-label="قيمة الدفعة" type="number" required min="0.001" max={left/1000} step="0.001" disabled={full} value={(full?left:p.amountFils)/1000} onChange={e=>setP({...p,amountFils:Math.round(Number(e.target.value)*1000)})}/></Field><label className="check-line"><Checkbox checked={full} onCheckedChange={v=>setFull(v===true)}/>كامل المبلغ</label><Field label="تاريخ السداد"><input aria-label="تاريخ السداد" type="date" required value={p.date} onChange={e=>setP({...p,date:e.target.value})}/></Field><Field label="مرجع السداد / ملاحظات" wide><textarea aria-label="مرجع السداد" maxLength={2000} value={p.notes} onChange={e=>setP({...p,notes:e.target.value})}/></Field></div><div className="form-footer"><SaveButton busy={busy}>تأكيد تسجيل الدفعة</SaveButton></div></form>;
}
function LeaveForm({ids:initialIds,kind:initialKind,s,busy,commit}:{ids:string[];kind:"annual"|"holiday";s:Snapshot;busy:boolean;commit:Commit}){
  const [ids,setIds]=useState(initialIds),[direction,setDirection]=useState("credit"),[entry,setEntry]=useState({kind:initialKind,days:1,date:today(),reason:""}),[confirmed,setConfirmed]=useState(false);
  const signed=direction==="credit"?entry.days:-entry.days;
  return <form onSubmit={async e=>{e.preventDefault();if(ids.length>1&&!confirmed)return;await commit({action:"leave.add",ids,entry:{...entry,days:signed}});}}><div className="form-grid">{ids.length<=1&&<Field label="الموظف" wide><Choice label="الموظف" value={ids[0]||""} onChange={v=>setIds(v?[v]:[])} options={[{value:"",label:"اختر الموظف"},...s.employees.map(e=>({value:e.id,label:e.name+" · "+e.code}))]}/></Field>}<Field label="نوع الرصيد"><Choice label="نوع الرصيد" value={entry.kind} options={[{value:"annual",label:"إجازة سنوية"},{value:"holiday",label:"راحة بديلة للأعياد"}]} onChange={v=>setEntry({...entry,kind:v as "annual"|"holiday"})}/></Field><Field label="نوع الحركة"><Choice label="نوع الحركة" value={direction} options={[{value:"credit",label:"إضافة إلى الرصيد"},{value:"debit",label:"خصم من الرصيد"}]} onChange={setDirection}/></Field><Field label="عدد الأيام لكل موظف"><input aria-label="عدد الأيام" required type="number" min="0.5" max="9999" step="0.5" value={entry.days} onChange={e=>setEntry({...entry,days:Number(e.target.value)})}/></Field><Field label="تاريخ الحركة"><input aria-label="تاريخ الحركة" required type="date" value={entry.date} onChange={e=>setEntry({...entry,date:e.target.value})}/></Field><Field label="السبب / اسم العيد *" wide><textarea aria-label="سبب الحركة" required minLength={2} maxLength={500} placeholder={entry.kind==="holiday"?"مثال: راحة بديلة عن عمل موثّق خلال عيد الفطر":"سبب الإضافة أو الإجازة المستخدمة"} value={entry.reason} onChange={e=>setEntry({...entry,reason:e.target.value})}/></Field></div>
    {!!ids.length&&<div className="preview-table"><Table><TableHeader><TableRow><TableHead>الموظف</TableHead><TableHead>قبل</TableHead><TableHead>بعد</TableHead></TableRow></TableHeader><TableBody>{s.employees.filter(e=>ids.includes(e.id)).map(e=>{const b=balance(e,s.leaves,entry.kind);return <TableRow key={e.id}><TableCell>{e.name}</TableCell><TableCell>{number(b)} يوم</TableCell><TableCell className={b+signed<0?"red-text":"purple-text"}>{number(b+signed)} يوم</TableCell></TableRow>;})}</TableBody></Table></div>}
    {ids.length>1&&<label className="check-line"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/>تأكيد تسجيل الحركة لكل موظف محدد ({ids.length}).</label>}<div className="form-footer"><SaveButton busy={busy}>تسجيل حركة الرصيد</SaveButton></div></form>;
}
