"use client";
import { useMemo, useRef, useState } from "react";
import { FileSpreadsheet, Upload, ArrowDownToLine, ArrowLeft, Check, FileCheck2, AlertCircle, X, LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Table, TableHeader, TableHead, TableRow, TableBody, TableCell } from "@/components/ui/table";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import { Snapshot, Employee, employeeFields, readableError, blankEmployee, validateEmployee } from "@/lib/hr";
import { ImportedSheet, employeeImportFields, guessMapping, mapRows } from "@/lib/excel";
import { Choice } from "./ui-parts";
import type { Commit } from "./forms";
import FinanceImport from "./finance-import";

export default function ImportPanel({s,busy,commit}:{s:Snapshot;busy:boolean;commit:Commit}){
  const [target,setTarget]=useState("employees");
  return <><div className="import-target"><strong>نوع البيانات</strong><Tabs dir="rtl" value={target} onValueChange={setTarget}><TabsList className="app-tabs"><TabsTrigger value="employees">الموظفون والأرصدة</TabsTrigger><TabsTrigger value="loan">القروض</TabsTrigger><TabsTrigger value="obligation">الخصومات</TabsTrigger></TabsList></Tabs></div>{target==="employees"?<EmployeeImport s={s} busy={busy} commit={commit}/>:<FinanceImport key={target} kind={target as "loan"|"obligation"} s={s} busy={busy} commit={commit}/>}</>;
}
function EmployeeImport({s,busy,commit}:{s:Snapshot;busy:boolean;commit:Commit}){
  const [sheets,setSheets]=useState<ImportedSheet[]>([]),[sheetIndex,setSheetIndex]=useState(0),[mapping,setMapping]=useState<string[]>([]),[mode,setMode]=useState("add"),[fileName,setFileName]=useState(""),[reading,setReading]=useState(false),[step,setStep]=useState(1),[confirmed,setConfirmed]=useState(false),[error,setError]=useState("");
  const input=useRef<HTMLInputElement>(null);const sheet=sheets[sheetIndex];
  const preview=useMemo(()=>{
    if(!sheet)return{rows:[] as Partial<Employee>[],errors:[] as string[]};const mapped=mapRows(sheet,mapping);const seen=new Set<string>();const result=[...s.employees];
    for(const [i,row] of mapped.rows.entries()){
      try{const code=(row.code||"").toUpperCase(),before=s.employees.find(e=>e.code===code);if(seen.has(code))throw Error("الرقم الوظيفي مكرر داخل الملف");seen.add(code);if(mode==="add"&&before)throw Error("رقم وظيفي موجود. اختر تحديث الموجودين.");if(mode==="update"&&!before)throw Error("الرقم الوظيفي غير موجود");const e=validateEmployee({...blankEmployee(),...before,...row,id:before?.id||crypto.randomUUID()},result,s.leaves);const index=result.findIndex(x=>x.id===e.id);if(index<0)result.push(e);else result[index]=e;}catch(err){mapped.errors.push(`صف ${i+2}: ${readableError(err)}`);}
    }
    if(!mapped.rows.length)mapped.errors.push("الورقة لا تحتوي صفوف بيانات.");return mapped;
  },[sheet,mapping,s.employees,s.leaves,mode]);
  async function read(file?:File){if(!file||reading||busy)return;setReading(true);setError("");setStep(1);setConfirmed(false);setSheets([]);try{const {parseWorkbook}=await import("@/lib/excel");const data=await parseWorkbook(file);setSheets(data);setSheetIndex(0);setMapping(guessMapping(data[0].headers));setFileName(file.name);setStep(2);}catch(e){setError(readableError(e));}finally{setReading(false);if(input.current)input.current.value="";}}
  async function template(){try{const {downloadTemplate}=await import("@/lib/excel");await downloadTemplate();}catch(e){toast.error(readableError(e));}}
  return <div className="import-layout"><section className="panel import-main"><div className="import-steps">{["رفع الملف","مطابقة الأعمدة","مراجعة وحفظ"].map((label,i)=><div className={step>=i+1?"current":""} key={label}><span>{step>i+1?<Check size={17}/>:i+1}</span><b>{label}</b>{i<2&&<ArrowLeft size={16}/>}</div>)}</div><div className="import-inner"><Tabs value={mode} onValueChange={v=>{setMode(v);setConfirmed(false);setStep(sheets.length?2:1);}} dir="rtl"><TabsList className="app-tabs"><TabsTrigger value="add">إضافة موظفين جدد</TabsTrigger><TabsTrigger value="update">تحديث الموظفين الموجودين</TabsTrigger></TabsList></Tabs><p className="form-hint">{mode==="add"?"أرقام وظيفية جديدة فقط. تُرفض السجلات المكررة.":"المطابقة بالرقم الوظيفي. الخلايا الفارغة تحتفظ بالقيمة الحالية."}</p>
  {step===1?<div className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void read(e.dataTransfer.files[0]);}}><span className="upload-symbol">{reading?<LoaderCircle size={32} className="spin"/>:<FileSpreadsheet size={35}/>}</span><h2>{reading?"جارٍ قراءة الملف…":"اسحب ملف Excel إلى هنا"}</h2><p>أو اختره من جهازك</p><Button disabled={reading||busy} className="primary-button" onClick={()=>input.current?.click()}><Upload size={17}/>اختيار ملف</Button><small>XLSX · حتى 5 ميجابايت · 500 موظف في العملية</small></div>:<><div className="file-selected"><span className="mini-icon mint"><FileSpreadsheet/></span><div><strong dir="auto">{fileName}</strong><small>{sheet?.rows.length} صف بيانات</small></div><Button variant="ghost" size="sm" disabled={busy} onClick={()=>input.current?.click()}>تغيير الملف</Button></div>{sheets.length>1&&<div className="sheet-picker"><label>ورقة العمل</label><Choice label="ورقة العمل" value={String(sheetIndex)} options={sheets.map((s,i)=>({value:String(i),label:s.name}))} onChange={v=>{setSheetIndex(Number(v));setMapping(guessMapping(sheets[Number(v)].headers));setStep(2);setConfirmed(false);}}/></div>}
  {step===2?<><h3>طابق أعمدة الملف مع بيانات الموظف</h3><div className="mapping-table"><Table><TableHeader><TableRow><TableHead>عمود Excel</TableHead><TableHead>قيمة من أول صف</TableHead><TableHead>الحقل في مسار</TableHead></TableRow></TableHeader><TableBody>{sheet?.headers.map((h,i)=><TableRow key={i}><TableCell><strong>{h}</strong></TableCell><TableCell className="muted">{sheet.rows[0]?.[i]?.slice(0,50)||"—"}</TableCell><TableCell><Choice label={"ربط العمود "+h} value={mapping[i]||"skip"} options={[{value:"skip",label:"تجاهل هذا العمود"},...employeeImportFields.map(f=>({value:f.key,label:f.label}))]} onChange={v=>{setMapping(m=>m.map((x,j)=>j===i?v:x));setConfirmed(false);}}/></TableCell></TableRow>)}</TableBody></Table></div><div className="form-footer"><Button className="primary-button" onClick={()=>setStep(3)}>مراجعة البيانات<ArrowLeft size={16}/></Button></div></>:<><div className={preview.errors.length?"import-result invalid":"import-result valid"}>{preview.errors.length?<AlertCircle/>:<FileCheck2/>}<div><strong>{preview.errors.length?"تحتاج البيانات إلى مراجعة":`${preview.rows.length} موظف جاهز ${mode==="add"?"للإضافة":"للتحديث"}`}</strong><p>{preview.errors.length?"لن يُحفظ أي صف قبل تصحيح جميع الأخطاء.":"راجع القيم التالية ثم أكّد الحفظ."}</p></div></div>{preview.errors.length>0&&<ul className="import-errors">{preview.errors.slice(0,30).map((e,i)=><li key={i}>{e}</li>)}{preview.errors.length>30&&<li>وأخطاء إضافية؛ صحّح الملف ثم أعد رفعه.</li>}</ul>}<div className="preview-table"><Table><TableHeader><TableRow><TableHead>الصف</TableHead>{mapping.filter(x=>x!=="skip").map((key,i)=><TableHead key={key+i}>{employeeFields.find(f=>f.key===key)?.label}</TableHead>)}</TableRow></TableHeader><TableBody>{preview.rows.slice(0,30).map((row,i)=><TableRow key={i}><TableCell>{i+2}</TableCell>{mapping.filter(x=>x!=="skip").map((key,j)=>{const v=row[key as keyof Employee];return <TableCell key={key+j}>{v===undefined?<span className="muted">{mode==="update"?"دون تغيير":"—"}</span>:key.endsWith("Fils")?Number(v)/1000:String(v)}</TableCell>;})}</TableRow>)}</TableBody></Table></div>{preview.rows.length>30&&<p className="form-hint">تُعرض أول 30 نتيجة؛ يجري التحقق من جميع الصفوف قبل الحفظ.</p>}<label className="check-line"><Checkbox checked={confirmed} disabled={!!preview.errors.length} onCheckedChange={v=>setConfirmed(v===true)}/>راجعت الملف وأوافق على {mode==="add"?"إضافة":"تحديث"} {preview.rows.length} موظف.</label><div className="form-footer"><Button variant="outline" disabled={busy} onClick={()=>{setStep(2);setConfirmed(false);}}>العودة للمطابقة</Button><Button className="primary-button" disabled={busy||!confirmed||!!preview.errors.length} onClick={async()=>{if(await commit({action:"employees.import",mode,rows:preview.rows})){setSheets([]);setStep(1);setConfirmed(false);setFileName("");}}}>{busy?<LoaderCircle size={17} className="spin"/>:<Check size={17}/>}تأكيد حفظ البيانات</Button></div></>}
  </>}
  <input ref={input} className="sr-only" type="file" accept=".xlsx" aria-label="اختيار ملف Excel" onChange={e=>void read(e.target.files?.[0])}/>{error&&<p role="alert" className="error-box">{error}</p>}
  </div></section><aside><div className="template-card"><span className="mini-icon"><FileSpreadsheet size={26}/></span><h2>بداية مرتّبة بملف جاهز</h2><p>قالب Excel عربي بجميع الحقول وإرشادات التعبئة.</p><Button variant="outline" onClick={()=>void template()}><ArrowDownToLine size={17}/>تنزيل قالب الموظفين</Button></div><div className="panel import-tips"><h3>قبل الاستيراد</h3><ol><li>الرقم الوظيفي مفتاح المطابقة، ويجب أن يكون فريداً.</li><li>التواريخ بصيغة YYYY-MM-DD أو كخلايا تاريخ.</li><li>المبالغ بالدينار، بثلاث منازل عشرية كحد أقصى.</li><li>الأرصدة الافتتاحية تستبدل القيم الافتتاحية السابقة عند التحديث.</li><li>لن يُعدّل الاستيراد سجلات القروض أو دفعاتها.</li></ol></div></aside></div>;
}
